# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_2(self):
    self.driver.get("https://www.rambler.ru/")
    self.vars["maxLength"] = "5000"
    self.vars["generatedString"] = self.driver.execute_script("return \'a\'.repeat(arguments[0])", self.vars["maxLength"])
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"query\"] ").send_keys(self.vars["generatedString"])
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']//button[@type=\'submit\']").click()
    elements = self.driver.find_elements(By.XPATH, "//*[contains(@class, \'Error\')]")
    assert len(elements) > 0
  
