# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test3XSS():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_3XSS(self):
    self.driver.get("https://www.rambler.ru/")
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"query\"] ").send_keys("<img src=x onerror=alert(1)>")
    self.driver.find_element(By.XPATH, "//div[@id=\'app\']//button[@type=\'submit\']").click()
    assert self.driver.switch_to.alert.text == "contains(*,\'угроза\')"
  
